twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        site_settings: '@App\Resolver\Page\SiteSettingsResolver'

when@test:
    twig:
        strict_variables: true
