version: '3.8'

services:
  el_db:
    container_name: el_db
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: elearning_platform
      MYSQL_DATABASE: elearning_platform
      MYSQL_USER: elearning_platform
      MYSQL_PASSWORD: elearning_platform
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  el_php:
    container_name: el_php
    platform: linux/x86_64
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/home
    depends_on:
      - el_db
  el_nginx:
    container_name: el_nginx
    platform: linux/x86_64
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./:/var/www/home
      - ./build/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - el_php
      - el_db
